### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by nuzayets**
## Motivation 

`rubocop-rspec` returns false-positive on RSpec/FilePath with VS Code Integration: 
https://github.com/rubocop/rubocop-rspec/pull/1099
https://github.com/rubocop/rubocop-rspec/issues/1091, fixed in v2.4.0.

`rubocop` complained about `ExcludedMethods`:
```
Warning: obsolete parameter `ExcludedMethods` (for `Metrics/BlockLength`) found in /home/coder/.rvm/gems/ruby-2.7.4/gems/glossgenius_style-0.1.13/default.yml
`ExcludedMethods` has been renamed to `IgnoredMethods`.
```

## Actions

1. Bumped `rubocop` and `rubocop-rspec` to latest
2. Change `ExcludedMethods` to `IgnoredMethods`
3.  `bundle update` to update within constraints
4. Bump GG style version

### CODE REVIEW

**Comment by ilyabyar** [comment]
@nuzayets  nicely done. 
Just FYI, we decided to remove this gem one day in https://glossgenius.atlassian.net/browse/EN-4354.

**Review by ilyabyar — APPROVED** [review]

**Comment by ilyabyar** [comment]
.. And just to make sure... you understand it: 
we have two rubocop configs, one of them is required, while the other one is preferable to pass for new files. Tha latter is not so strict and enforced because we didn't establish a convention rule-by-rule yet.

**Review by dominikgrygiel — APPROVED** [review]
I think we could remove it already, now that we have the required config. What do you think?

**Review by StalemateInc — APPROVED** [review]
I'm fine with removing this repo, just don't forget to move the dependencies to `core-api` to stop using this gem completely.

**Comment by ilyabyar** [comment]
Yeah, let's do it. Just need to move some parts of existing config to `.rubocop.yml`

**Comment by nuzayets** [comment]
Ok I'll merge this for now and it will become irrelevant once that's done

**Pull request merged**
